# Generated by Django 3.2.25 on 2024-05-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='textarea',
            new_name='message',
        ),
    ]
