# Generated by Django 3.2.25 on 2024-05-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="product_size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
